import type {Metadata} from 'next';
import './globals.css';
import Navigate from '../components/home/navigate';
import HomeNav from '../components/home/homeNav';
import {TiThMenuOutline} from 'react-icons/ti';

export const metadata: Metadata = {
  title: 'Mytoon2019',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <footer className="main_footer">
          <HomeNav />
          <Navigate />
          <TiThMenuOutline style={{marginRight: 30, width: 45, height: 45}} />
        </footer>
      </body>
    </html>
  );
}
